import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast'
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import UserContextProvider from "./context/UserContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <Navbar/>
          {children}
          <Toaster/>
          <Footer/>
        </UserContextProvider>
      </body>
    </html>
  );
}
